/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  UIsetSidebar: [
    {
      type: "category",
      label: "UIset",
      items: [
        "UIset/index",
        "UIset/introduction",
        "UIset/project",
        "UIset/setting/animation",
        "UIset/setting/ring",
        "UIset/setting/vrc",
        "UIset/texture_edit/index",
        "UIset/FAQ",
      ],
    },
  ],
};

module.exports = sidebars;
